export const STATIC_HOME_CONTENT_QUERY = `
*[_type == "staticHomeContent"][0]{
  _id,
  _type,
  publicHero{
    title,
    subtitle,
    companiesButtonText,
    suppliersButtonText
  },
  businessTypesSection{
    title
  },
  featuredCompaniesTitle,
  featuredSuppliersTitle,
  productCategoriesTitle,
  heroSearchTitle,
  heroVideo{
    desktop{asset->{url}},
    mobile{asset->{url}}
  },
  discover{
    title,
    description,
    image{
      asset->{
        _id,
        url,
        metadata{
          dimensions,
          lqip
        }
      },
      hotspot,
      crop
    }
  },
  how{
    title,
    subtitle,
    steps[]{
      title,
      description,
      icon{asset->{url}}
    }
  },

  why{
    title,
    subtitle,
    features[]{
      title,
      description,
      icon{asset->{url}}
    }
  },

  faq[]{
    q,
    a,
    target
  },
  categoriesTitle,
  faqTitle,
  blogTitle,
  featuredCompanies[]->{
    "id": coalesce(tenantId, slug.current),
    tenantId,
    name,
    rating,
    ratingCount,
    logo{
      asset->{
        _id,
        url,
        metadata{
          dimensions,
          lqip
        }
      },
      hotspot,
      crop
    },
    "description": pt::text(description)
  },
  featuredSuppliers[]->{
    "id": coalesce(tenantId, slug.current),
    tenantId,
    name,
    rating,
    ratingCount,
    logo{
      asset->{
        _id,
        url,
        metadata{
          dimensions,
          lqip
        }
      },
      hotspot,
      crop
    },
    "description": pt::text(description)
  }
}`;
